export const dataBooks = [{
    id: "83223jd2-6y2e-46c2-aed5-35gee321f8ba",
    imageUrlPT: "",
    titlePT: "Pan Tadeusz",
    authorPT: "",
    contentPT: "",
    date: "",
}, {
    id: "fej93jnj-5hy2-48d3-a4f8-uew8u8w2sass",
    imageUrlDZIII: "",
    titleDZIII: "",
    authorDZIII: "",
    contentDZIII: "",
    date: "",
}, {
    id: "93rwefwfw-3da1-ief3-bd96-9efwej8jfjw",
    imageUrlLL: "",
    titleLL: "",
    authorLL: "",
    contentLL: "",
    date: "",
}, {
    id: "i9wierwpo-udu2-431f-bd56-83u8jwewdas5",
    imageUrlFD: "",
    titleFD: "",
    authorFD: "",
    contentFD: "",
    date: "",
}, {
    id: "efoef32fw-u892-471f-bd96-deuw89wedu2e",
    imageUrlWS: "",
    titleWS: "",
    authorWS: "",
    contentWS: "",
    date: "",
}];